[2024-11-14T15:22:38.061+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T15:22:38.329+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T15:22:38.541+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T15:22:38.554+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-14T15:22:38.935+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2024-11-13 00:00:00+00:00
[2024-11-14T15:22:39.300+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=129) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T15:22:39.302+0000] {standard_task_runner.py:72} INFO - Started process 184 to run task
[2024-11-14T15:22:39.451+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'inaccurate', 'scheduled__2024-11-13T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/hello_world_dag.py', '--cfg-path', '/tmp/tmp9sxqxjyb']
[2024-11-14T15:22:39.585+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask inaccurate
[2024-11-14T15:22:40.736+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-13T00:00:00+00:00 [running]> on host e14bbb8637e8
[2024-11-14T15:22:43.043+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-13T00:00:00+00:00'
[2024-11-14T15:22:43.068+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-14T15:22:43.097+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-14T15:22:43.103+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2024-11-14 15:22:38.338618+00:00
[2024-11-14T15:22:43.116+0000] {logging_mixin.py:190} INFO - Dag name:hello_world_dag and current dag run status:running
[2024-11-14T15:22:43.124+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-14T15:22:43.138+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-14T15:22:43.147+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-11-14T15:22:43.843+0000] {subprocess.py:99} INFO - Output:
[2024-11-14T15:22:43.892+0000] {subprocess.py:106} INFO - inaccurate
[2024-11-14T15:22:43.917+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-14T15:22:44.272+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-14T15:22:44.288+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=hello_world_dag, task_id=inaccurate, run_id=scheduled__2024-11-13T00:00:00+00:00, execution_date=20241113T000000, start_date=20241114T152238, end_date=20241114T152244
[2024-11-14T15:22:44.512+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-14T15:22:44.579+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-14T15:22:44.609+0000] {logging_mixin.py:190} INFO - Dag name:hello_world_dag queued_at:2024-11-14 15:21:24.230457+00:00
[2024-11-14T15:22:44.639+0000] {logging_mixin.py:190} INFO - Task hostname:e14bbb8637e8 operator:BashOperator
[2024-11-14T15:22:45.247+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-14T15:22:45.394+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T15:22:45.409+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
