[2024-11-14T15:22:32.767+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-14T15:22:33.369+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.training_model_A scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T15:22:33.683+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.training_model_A scheduled__2024-11-13T00:00:00+00:00 [queued]>
[2024-11-14T15:22:33.707+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-14T15:22:34.419+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): training_model_A> on 2024-11-13 00:00:00+00:00
[2024-11-14T15:22:34.954+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=130) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T15:22:34.990+0000] {standard_task_runner.py:72} INFO - Started process 179 to run task
[2024-11-14T15:22:34.856+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'training_model_A', 'scheduled__2024-11-13T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/hello_world_dag.py', '--cfg-path', '/tmp/tmppjeylpzg']
[2024-11-14T15:22:35.046+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask training_model_A
[2024-11-14T15:22:35.652+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.training_model_A scheduled__2024-11-13T00:00:00+00:00 [running]> on host e14bbb8637e8
[2024-11-14T15:22:41.617+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-11-14T15:22:41.643+0000] {process_utils.py:132} INFO - Sending 15 to group 179. PIDs of all processes in the group: [179]
[2024-11-14T15:22:41.689+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 179
[2024-11-14T15:22:42.458+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=179, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='15:22:33') (179) terminated with exit code -15
[2024-11-14T15:22:42.466+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-11-14T15:22:42.688+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T15:22:45.061+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2024-11-14T15:22:45.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
