[2024-11-18T19:03:27.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T19:03:28.393+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T19:03:28.876+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-17T00:00:00+00:00 [queued]>
[2024-11-18T19:03:28.877+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-18T19:03:29.541+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): inaccurate> on 2024-11-17 00:00:00+00:00
[2024-11-18T19:03:29.825+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=82) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T19:03:29.954+0000] {standard_task_runner.py:72} INFO - Started process 105 to run task
[2024-11-18T19:03:29.955+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'hello_world_dag', 'inaccurate', 'scheduled__2024-11-17T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/hello_world_dag.py', '--cfg-path', '/tmp/tmp_0luusbx']
[2024-11-18T19:03:30.148+0000] {standard_task_runner.py:105} INFO - Job 27: Subtask inaccurate
[2024-11-18T19:04:13.325+0000] {task_command.py:467} INFO - Running <TaskInstance: hello_world_dag.inaccurate scheduled__2024-11-17T00:00:00+00:00 [running]> on host e14bbb8637e8
[2024-11-18T19:04:17.451+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hello_world_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T00:00:00+00:00'
[2024-11-18T19:04:17.547+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T19:04:17.547+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T19:04:17.548+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2024-11-18 19:03:28.519016+00:00
[2024-11-18T19:04:17.548+0000] {logging_mixin.py:190} INFO - Dag name:hello_world_dag and current dag run status:running
[2024-11-18T19:04:17.548+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T19:04:17.668+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-11-18T19:04:17.731+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-11-18T19:04:19.134+0000] {subprocess.py:99} INFO - Output:
[2024-11-18T19:04:19.404+0000] {job.py:229} INFO - Heartbeat recovered after 53.89 seconds
[2024-11-18T19:04:19.533+0000] {subprocess.py:106} INFO - inaccurate
[2024-11-18T19:04:19.552+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-11-18T19:04:20.004+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T19:04:20.005+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=hello_world_dag, task_id=inaccurate, run_id=scheduled__2024-11-17T00:00:00+00:00, execution_date=20241117T000000, start_date=20241118T190328, end_date=20241118T190420
[2024-11-18T19:04:21.061+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T19:04:21.132+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T19:04:21.169+0000] {logging_mixin.py:190} INFO - Dag name:hello_world_dag queued_at:2024-11-18 19:02:07.063165+00:00
[2024-11-18T19:04:21.177+0000] {logging_mixin.py:190} INFO - Task hostname:e14bbb8637e8 operator:BashOperator
[2024-11-18T19:04:22.201+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T19:04:22.222+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
